language: node_js

node_js:
  - "9"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
    
script:
  - npm test
  
after_success:
  - bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scripts/ff-start-travis.sh)
