language: node_js

node_js:
  - "9"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
    
script:
  - npm test
  
after_success:
  - bash <(curl -s https://scripts.scantist.com/staging/ci-travis.sh)
