language: node_js
node_js:
  - "8.9"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn

after_success:
  - bash <(curl -s https://s3-ap-southeast-1.amazonaws.com/ci-scripts/ff-start-travis.sh)
